---
title: "carr-plots"
author: "Levi Carr"
format: html
---
```{r Libraries}
#| include: false
library(ncdf4)
library(tidyverse)
library(mosaic)
library(ggformula)
library(rethinking)
library(rstan)
library(CalvinBayes)
library(bayesplot)
library(tidybayes)
theme_set(theme_classic(base_size=16))
```

```{r Read In RDS File}
cirrus_fit <- readRDS('cirrus_fit_2')
cirrus_fit_samps <- as.data.frame(cirrus_fit) |> rename(Mean_Reff = b0,
                                                        No_Ice = `b1[1]`,
                                                        Some_Ice = `b1[2]`,
                                                        All_Ice = `b1[3]`,
                                                        log_lik = `lp__`)
```

```{r Check Convergence}
cirrus_fit
mcmc_rank_overlay(cirrus_fit, pars=c('b0', 'b1[1]','b1[2]','b1[3]'))
mcmc_trace(cirrus_fit, pars=c('b0', 'b1[1]','b1[2]','b1[3]'))
```

```{r Convergence Check II}
WAIC(cirrus_fit, pointwise = TRUE)
```

```{r Plot Priors}
gf_dens(~Mean_Reff, data=cirrus_fit_samps, linewidth = 2, color = 'black') |>
  gf_labs(title='Mean R_eff for Cirrus Clouds on March 30, 2025', ylab=('Posterior Density'))
gf_dens(~No_Ice, data=cirrus_fit_samps, linewidth = 2, color = 'black') |>
  gf_labs(title='Mean R_eff for No-Ice Cirrus Clouds on March 30, 2025', ylab=('Posterior Density'))
gf_dens(~Some_Ice, data=cirrus_fit_samps, linewidth = 2, color='black') |>
  gf_labs(title='Mean R_eff for Some-Ice Cirrus Clouds on March 30, 2025', ylab=('Posterior Density'))
gf_dens(~All_Ice, data=cirrus_fit_samps, linewidth = 2, color='black') |>
  gf_labs(title='Mean R_eff for All-Ice Cirrus Clouds on March 30, 2025', ylab=('Posterior Density'))
```

```{r Plot Prior Diffs}
gf_dens(~(Some_Ice-No_Ice), data=cirrus_fit_samps, linewidth=2, color='blue')|> gf_labs(title="R_eff Difference Between Some-Ice and No-Ice Cirrus Clouds",
                                                              ylab("Posterior Density"))
gf_dens(~(All_Ice-Some_Ice), data=cirrus_fit_samps, linewidth=2, color='royalblue')|> gf_labs(title="R_eff Difference Between All-Ice and Some-Ice Cirrus Clouds",
                                                              ylab("Posterior Density"))
gf_dens(~(All_Ice-No_Ice), data=cirrus_fit_samps, linewidth=2, color='skyblue')|> gf_labs(title="R_eff Difference Between All-Ice and No-Ice Cirrus Clouds",
                                                              ylab("Posterior Density"))
```


