---
title: "STAT 341 Final Report"
author: "Levi carr"
format: html
---
### Research Question
In cirrus clouds, how does the effective radius of the droplets change with ice composition? 

### Causal Diagram
Draw it, and interpret it to determine which predictors are in and out of your model! May be drawn in R using dagitty(), or in other software if moderators are included

### ADD-ON: Categorical predictor(s) 
I have a post processing variable from the data set called `cf_ice` which describes how much of the cloud is ice. `cf_ice` ranges from 0 to 1 where 0 is an all liquid water cloud and 1 is an all ice cloud. By looking at the distribution of `cf_ice` on other days, a pattern of two high density peaks around 0 and 1 with a few cases in between is predominant. I therefore separate the data into three groups: "no ice" (0.05 > `cf_ice`), "some ice" (0.05 < `cf_ice` < 0.95), and "all ice" (`cf_ice` > 0.95).

### Rationales for Priors
In paragraphs or bullet points, explain how and why you chose the priors. Include rationales for which distributions were used as well as parameter values chosen. If any sources were used for prior information, cite them in the text and provide a works cited section at the end. MLA style or any other consistent citation style is ok.

### Model Description 
 $$
 R_{eff} \sim \mathrm{Gamma}(\mu_i, \sigma)
 $$
 $$
 \ln(\mu_i) = \beta_0 + \beta_1 \left[ \text{ice_fraction}_i \right]
 $$
 $$
 \beta_0 \sim \mathrm{Normal}(\ln(20), \ln(e))
 $$
 $$
 \beta_1[\text{no ice}] \sim \mathrm{Normal}(-0.1, 0.2)
 $$
 $$
 \beta_1[\text{some ice}] \sim \mathrm{Normal}(0.005, 0.4)
 $$
 $$
 \beta_1[\text{all ice}] \sim \mathrm{Normal}(0.1, 0.2)
 $$
 $$
 \sigma \sim \mathrm{Lognormal}(\ln(15), 0.5)
 $$
### Prior Predictive Distribution - show and interpret 
If your process of defining priors was iterative, you can combine this section with the “Prior Rationales” section and walk the reader through your entire process.

### Fit your Model 
You can fit via quadratic approximation (quap()) or MCMC (introduced in class starting 3/20). Some add-ons are only possible if you use MCMC (a more professional approach).

### Present the Posterior - show and interpret
You may include any graphs or summary statistics of your choice that you think are useful in understanding the posterior.

### Model Comparison - show and interpret any necessary 
Completing this step may require fitting additional models that include some subset of your full set of predictors.

### Discussion/Answer to Research Question 
Provide a clear answer to your question of interest, referring to evidence presented earlier.

### ADD-ON: Show and discuss diagnostics for fit convergence 	
This is only possible if your model was fitted using MCMC rather than quap()

### ADD-ON: Model is a GLM, or otherwise uses non-Normal distribution(s) to help define the likelihood 
This is about the distributions used to define the likelihood, not the priors.

This model is a GLM. The likelihood for droplet size distributions (DSDs) which produce $\mathrm{R_eff}$ is a Gamma distribution (Ulbrich 1983 and references therein). This is because  I assume this distribution holds for clouds of different phase. 

### ADD-ON: Github
A GitHub repository was used. Data and files used here can be found at https://github.com/carr-levi-a/calvinbayes25_atmsci.

